wikalloy {
    numInstances = 500
    numLoads     = 50
    numQueries   = 1000
    outputPath   = "/opt/output/"
}

mysql {
    uri = "jdbc:mysql://mysql:3306/"
	username = "root"
	password = "mysqltest"
}

alloy {
	solutionFolderPath = "/opt/solutions/"
	solutionMax = 10000000
}

spark {
	master = "spark://spark-master:7077"
}
